---
# Source: reloader/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: reloader
    group: com.stakater.platform
    provider: stakater
    version: 0.0.10
    chart: "reloader-0.0.10"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: reloader
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: reloader
      group: com.stakater.platform
      provider: stakater
  template:
    metadata:
      labels:
        app: reloader
        group: com.stakater.platform
        provider: stakater
    spec:
      containers:
      - env:
        image: "stakater/reloader:0.0.10"
        imagePullPolicy: IfNotPresent
        name: reloader
      serviceAccountName: reloader
              
