---
# Source: reloader/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: reloader
    chart: "reloader-0.0.19"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: reloader

