---
# Source: reloader/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: reloader-reloader
    chart: "reloader-v0.0.56"
    release: "reloader"
    heritage: "Tiller"
  name: reloader-reloader

