---
# Source: reloader/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-namespace: "default"
    meta.helm.sh/release-name: "reloader"
  labels:
    app: reloader-reloader
    chart: "reloader-v0.0.73"
    release: "reloader"
    heritage: "Tiller"
    app.kubernetes.io/managed-by: "Tiller"
  name: reloader-reloader

