apiVersion: v1
name: reloader
description: Reloader chart that runs on kubernetes
version: 2.1.2
appVersion: v1.4.1
keywords:
  - Reloader
  - kubernetes
home: https://github.com/stakater/Reloader
sources:
  - https://github.com/stakater/Reloader
icon: https://raw.githubusercontent.com/stakater/Reloader/master/assets/web/reloader-round-100px.png
maintainers:
  - name: Stakater
    email: hello@stakater.com
  - name: rasheedamir
    email: rasheed@stakater.com
  - name: faizanahmad055
    email: faizan@stakater.com
