name: Pull Request for Documentation Changes

on:
  pull_request:
    branches:
      - master
    paths:
      - '.markdownlint.yaml'
      - '.vale.ini'
      - 'Dockerfile-docs'
      - 'docs-nginx.conf'
      - 'docs/**'
      - 'theme_common'
      - 'theme_override'

jobs:
  qa:
    uses: stakater/.github/.github/workflows/pull_request_doc_qa.yaml@v0.0.122
    with:
      MD_CONFIG: .github/md_config.json
      DOC_SRC: docs
      MD_LINT_CONFIG: .markdownlint.yaml
  build:
    uses: stakater/.github/.github/workflows/pull_request_container_build.yaml@v0.0.122
    with:
      DOCKER_FILE_PATH: Dockerfile-docs
      CONTAINER_REGISTRY_URL: ghcr.io/stakater
    secrets:
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.GHCR_USERNAME }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }}
